/* 精准回滚：只恢复本次66条weighted_sales，且当前值必须仍等于重算后值。 */
SET @restored_weighted_rows = 0;
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='凤改改_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='凤改改_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='合计_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='合计_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='嘉讲_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='嘉讲_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='培仰_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='培仰_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='星魁_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='星魁_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='盾盟_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='盾盟_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='绝佳_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='绝佳_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='聪冲冲_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='聪冲冲_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='融利_JP_B0CJVFJMVF_20260718' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=9 WHERE shop_country_asin_date='融利_JP_B0CJVFJMVF_20260720' AND (weighted_sales <=> 8.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='伟春_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='合计_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='嫣冉_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='极画/南挣北赚_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='绘影_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=59.4 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260712' AND (weighted_sales <=> 59.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.3 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260713' AND (weighted_sales <=> 58.2);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.2 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260714' AND (weighted_sales <=> 57.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=57.6 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260715' AND (weighted_sales <=> 57.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.5 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260716' AND (weighted_sales <=> 58.3);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=58.2 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260717' AND (weighted_sales <=> 58.1);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.6 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260718' AND (weighted_sales <=> 56.5);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
UPDATE daily_sales SET weighted_sales=56.1 WHERE shop_country_asin_date='谷翰/嘉兴_US_B0FB3P6H48_20260719' AND (weighted_sales <=> 55.9);
SET @restored_weighted_rows = @restored_weighted_rows + ROW_COUNT();
SELECT @restored_weighted_rows AS restored_weighted_rows;
